name: clean_breathe
description: Pollution App

publish_to: 'none' # Remove this line if you plan to publish your app.

environment:
  sdk: ">=3.0.0 <4.0.0" # Adjust this according to your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  geocoding: ^2.0.0
  http: ^0.13.6
  provider: ^6.1.2
  font_awesome_flutter: ^10.0.0
  icon_decoration: ^2.1.0
  flutter_map_marker_cluster: any
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true